name = "QuixoticSimulating"
uuid = "fc340e6e-bb22-472c-9822-6a6ca0187659"
authors = ["Braden D. Kelly"]
version = "0.1.0"

[compat]
julia = "1.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
